version: 2

sources:
  - name: northwind
    database: Northwind      # حتماً ست کن
    schema: dbo              # در SQL Server = dbo
    quoting:
      identifier: true       # برای نام‌های با فاصله/حروف بزرگ
    tables:
      - name: customers
        identifier: Customers
      - name: orders
        identifier: Orders
      - name: products
        identifier: Products
      - name: order_details
        identifier: "Order Details"   # چون فاصله دارد
