# docker-compose.yml
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql2022
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ng!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    # (اختیاری) محدودیت رم/CPU در dev
    deploy:
      resources:
        limits:
          memory: 4g
volumes:
  mssql_data:
